### ISSUE TITLE
Add IBM Cloud Object Storage in storage Backend

### ISSUE THREAD

**Issue by MourIdri** [strongloop/loopback-example-storage#21]
### Bug or feature request

- [ ] Bug
- [ x] Feature request

### Description of feature (or steps to reproduce if bug)

Today, are supported : 

    Amazon
    Rackspace
    Openstack
    Azure

Is it possible to add IBM CLoud object storage ( S3 compliant storage ) as an endpoint ? 
https://ibm-public-cos.github.io/crs-docs/

### Expected result

Have IBM COS as a storage endpoint.

**Comment by crandmck** [comment]
@raymondfeng ^

I think this issue actually belongs in https://github.com/strongloop/loopback-component-storage

**Comment by srova** [comment]
For anyone still interested, we added the support for COS to pkgcloud library:

https://github.com/pkgcloud/pkgcloud/pull/625
