### ISSUE TITLE
Could you make an example-4.0 for Loopback 4?

### ISSUE THREAD

**Issue by anhvoleduy** [strongloop/loopback-example-storage#25]
# Description/Steps to reproduce
Loopback 4 is about to productive and developer are working on Loopback 4 want to create a Post method to upload the file also.

# Expected result
example-4.0 for Loopback 4

**Comment by anhvoleduy** [comment]
Loopback team is implementing this feature: https://github.com/strongloop/loopback-next/pull/1880
Hope we will have it soon.

**Comment by dhmlau** [comment]
@anhvoleduy , thanks for finding out the corresponding PR. Let me mark this as `in progress` as the PR is under review.  Thanks.

**Comment by dhmlau** [comment]
The corresponding PR should be https://github.com/strongloop/loopback-next/pull/1936, and it has been merged.  Please also see @raymondfeng's recent blog post regarding this topic: https://strongloop.com/strongblog/the-journey-to-extensible-request-body-parsing/

**Comment by anhvoleduy** [comment]
Thanks @dhmlau 
Please help me close this issue if you thinks the work was done

**Comment by dhmlau** [comment]
Closing as resolved. Thanks!

**Comment by activedecay** [comment]
I'm having trouble reading [the blog post mentioned above](https://strongloop.com/strongblog/the-journey-to-extensible-request-body-parsing/) and drawing the connection to how it closes this issue. How do I use the loopback-component-storage project in an LB4 application?
