### ISSUE TITLE
Not able to upload on S3

### ISSUE THREAD

**Issue by RameshJhajharia** [strongloop/loopback-example-storage#5]
I cloned the example and tried running it. It is working perfectly when choose the provider in datasource as filesystem.

Then I updated key and key id for amazon in providers.json and changed the provider to amazon in datasource, it gave me following error:

Failed to create a multipart upload on S3: {"message":"Missing credentials in config","stack":"TimeoutError: Missing credentials in config\n    at ClientRequest.<anonymous> (/loopback-example-storage-master/example-2.0/node_modules/loopback-component-storage/node_modules/pkgcloud/node_modules/aws-sdk/lib/http/node.js:56:34)\n    at ClientRequest.g (events.js:260:16)\n    at emitNone (events.js:67:13)\n    at ClientRequest.emit (events.js:166:7)\n    at Socket.emitTimeout (_http_client.js:534:10)\n    at Socket.g (events.js:260:16)\n    at emitNone (events.js:67:13)\n    at Socket.emit (events.js:166:7)\n    at Socket._onTimeout (net.js:318:8)\n    at _runOnTimeout (timers.js:515:11)","code":"CredentialsError","time":"2016-08-18T12:11:42.947Z","originalError":{"message":"Could not load credentials from any providers","code":"CredentialsError","time":"2016-08-18T12:11:42.946Z","originalError":{"message":"Connection timed out after 1000ms","code":"TimeoutError","time":"2016-08-18T12:11:42.946Z"}}}

**Comment by mandadimuralidharreddy** [comment]
in datasource.json file for s3 config obj you need to add 2 values "key":"you  amazon secret key ", "keyId": "your amazon access key"
